// Per-sport presets: positions, attribute sets, OVR weight profiles,
// grade-sheet categories, and stat definitions. Football is the default.

export type AttributeSpec = { key: string; name: string; category: string };
export type StatDef = { key: string; label: string; group: string };

// A starting-ratings profile assignable when adding/editing a player.
// Attributes start at 60, get `all` added across the board, then per-key
// boosts (which may be negative) on top.
export type Archetype = {
  key: string;
  name: string;
  description: string;
  all?: number;
  boosts: Record<string, number>;
};

export type SportPreset = {
  positions: string[];
  attributes: AttributeSpec[];
  positionWeights: Record<string, Record<string, number>>;
  gradeCategories: Record<string, string[]>;
  statDefs: StatDef[];
  archetypes: Archetype[];
};

export const SPORTS = ["Football", "Basketball", "Soccer", "Baseball"] as const;

const FOOTBALL: SportPreset = {
  positions: ["QB", "RB", "FB", "WR", "TE", "OT", "OG", "C", "DE", "DT", "LB", "CB", "S", "K", "P", "LS", "ATH"],
  attributes: [
    { key: "speed", name: "Speed", category: "Physical" },
    { key: "acceleration", name: "Acceleration", category: "Physical" },
    { key: "agility", name: "Agility", category: "Physical" },
    { key: "strength", name: "Strength", category: "Physical" },
    { key: "jumping", name: "Jumping", category: "Physical" },
    { key: "stamina", name: "Stamina", category: "Physical" },
    { key: "awareness", name: "Awareness", category: "Mental" },
    { key: "playRecognition", name: "Play Recognition", category: "Mental" },
    { key: "discipline", name: "Discipline", category: "Mental" },
    { key: "coachability", name: "Coachability", category: "Mental" },
    { key: "throwPower", name: "Throw Power", category: "Ball Skills" },
    { key: "throwAccuracy", name: "Throw Accuracy", category: "Ball Skills" },
    { key: "catching", name: "Catching", category: "Ball Skills" },
    { key: "carrying", name: "Carrying", category: "Ball Skills" },
    { key: "ballSecurity", name: "Ball Security", category: "Ball Skills" },
    { key: "runBlock", name: "Run Block", category: "Blocking" },
    { key: "passBlock", name: "Pass Block", category: "Blocking" },
    { key: "impactBlocking", name: "Impact Blocking", category: "Blocking" },
    { key: "tackling", name: "Tackling", category: "Defense" },
    { key: "blockShedding", name: "Block Shedding", category: "Defense" },
    { key: "manCoverage", name: "Man Coverage", category: "Defense" },
    { key: "zoneCoverage", name: "Zone Coverage", category: "Defense" },
    { key: "pursuit", name: "Pursuit", category: "Defense" },
    { key: "kickPower", name: "Kick Power", category: "Kicking" },
    { key: "kickAccuracy", name: "Kick Accuracy", category: "Kicking" },
    { key: "toughness", name: "Toughness", category: "Intangibles" },
    { key: "leadership", name: "Leadership", category: "Intangibles" },
    { key: "effort", name: "Effort / Motor", category: "Intangibles" },
  ],
  positionWeights: {
    QB: { throwAccuracy: 25, throwPower: 15, awareness: 15, playRecognition: 10, speed: 5, agility: 5, ballSecurity: 5, leadership: 10, effort: 5, coachability: 5 },
    RB: { speed: 18, acceleration: 12, agility: 12, carrying: 10, ballSecurity: 12, strength: 8, awareness: 8, catching: 5, effort: 10, toughness: 5 },
    FB: { strength: 18, runBlock: 15, impactBlocking: 12, carrying: 8, ballSecurity: 8, speed: 8, awareness: 10, toughness: 12, effort: 9 },
    WR: { speed: 18, catching: 20, agility: 12, acceleration: 10, jumping: 8, awareness: 10, ballSecurity: 7, effort: 10, coachability: 5 },
    TE: { catching: 15, runBlock: 12, passBlock: 8, strength: 10, speed: 10, awareness: 10, jumping: 5, ballSecurity: 5, toughness: 10, effort: 15 },
    OT: { passBlock: 22, runBlock: 18, strength: 15, awareness: 12, agility: 8, playRecognition: 5, toughness: 10, effort: 10 },
    OG: { runBlock: 22, passBlock: 16, strength: 17, awareness: 10, agility: 5, impactBlocking: 10, toughness: 10, effort: 10 },
    C: { runBlock: 18, passBlock: 16, strength: 14, awareness: 16, playRecognition: 8, impactBlocking: 5, leadership: 8, toughness: 7, effort: 8 },
    DE: { blockShedding: 16, pursuit: 14, strength: 14, speed: 10, acceleration: 10, tackling: 12, playRecognition: 6, toughness: 8, effort: 10 },
    DT: { blockShedding: 20, strength: 20, tackling: 12, pursuit: 8, awareness: 8, playRecognition: 8, toughness: 12, effort: 12 },
    LB: { tackling: 18, playRecognition: 14, pursuit: 12, speed: 10, strength: 10, zoneCoverage: 8, blockShedding: 8, awareness: 6, toughness: 6, effort: 8 },
    CB: { manCoverage: 20, speed: 18, agility: 12, zoneCoverage: 10, acceleration: 10, playRecognition: 8, tackling: 6, jumping: 6, effort: 10 },
    S: { zoneCoverage: 16, tackling: 14, playRecognition: 14, speed: 12, manCoverage: 10, pursuit: 10, awareness: 8, jumping: 4, effort: 12 },
    K: { kickAccuracy: 35, kickPower: 30, awareness: 10, discipline: 10, toughness: 5, coachability: 10 },
    P: { kickPower: 32, kickAccuracy: 32, awareness: 10, discipline: 11, coachability: 15 },
    LS: { discipline: 25, awareness: 20, strength: 15, passBlock: 10, toughness: 10, coachability: 20 },
    ATH: { speed: 15, agility: 12, acceleration: 10, strength: 10, awareness: 12, catching: 6, tackling: 6, effort: 15, coachability: 14 },
  },
  gradeCategories: {
    QB: ["Ball Skills", "Mental", "Physical", "Intangibles"],
    RB: ["Ball Skills", "Physical", "Mental", "Intangibles"],
    FB: ["Blocking", "Ball Skills", "Physical", "Intangibles"],
    WR: ["Ball Skills", "Physical", "Mental", "Intangibles"],
    TE: ["Ball Skills", "Blocking", "Physical", "Intangibles"],
    OT: ["Blocking", "Physical", "Mental", "Intangibles"],
    OG: ["Blocking", "Physical", "Mental", "Intangibles"],
    C: ["Blocking", "Physical", "Mental", "Intangibles"],
    DE: ["Defense", "Physical", "Mental", "Intangibles"],
    DT: ["Defense", "Physical", "Mental", "Intangibles"],
    LB: ["Defense", "Physical", "Mental", "Intangibles"],
    CB: ["Defense", "Physical", "Mental", "Intangibles"],
    S: ["Defense", "Physical", "Mental", "Intangibles"],
    K: ["Kicking", "Mental", "Intangibles"],
    P: ["Kicking", "Mental", "Intangibles"],
    LS: ["Blocking", "Mental", "Intangibles"],
    ATH: ["Physical", "Mental", "Ball Skills", "Defense", "Intangibles"],
  },
  statDefs: [
    { key: "passCmp", label: "Completions", group: "Passing" },
    { key: "passAtt", label: "Attempts", group: "Passing" },
    { key: "passYds", label: "Pass Yds", group: "Passing" },
    { key: "passTds", label: "Pass TDs", group: "Passing" },
    { key: "passInts", label: "INTs Thrown", group: "Passing" },
    { key: "rushAtt", label: "Carries", group: "Rushing" },
    { key: "rushYds", label: "Rush Yds", group: "Rushing" },
    { key: "rushTds", label: "Rush TDs", group: "Rushing" },
    { key: "recCatches", label: "Receptions", group: "Receiving" },
    { key: "recYds", label: "Rec Yds", group: "Receiving" },
    { key: "recTds", label: "Rec TDs", group: "Receiving" },
    { key: "fumbles", label: "Fumbles", group: "Ball Security" },
    { key: "tackles", label: "Tackles", group: "Defense" },
    { key: "tfl", label: "TFL", group: "Defense" },
    { key: "sacks", label: "Sacks", group: "Defense" },
    { key: "defInts", label: "INTs", group: "Defense" },
    { key: "ffum", label: "Forced Fum", group: "Defense" },
    { key: "fgMade", label: "FG Made", group: "Kicking" },
    { key: "fgAtt", label: "FG Att", group: "Kicking" },
    { key: "xpMade", label: "XP Made", group: "Kicking" },
  ],
  archetypes: [
    { key: "speedster", name: "Speedster", description: "Elite burst and quickness; strength and polish still coming", boosts: { speed: 18, acceleration: 16, agility: 14, jumping: 8, stamina: 6, strength: -6, awareness: -4 } },
    { key: "power", name: "Power", description: "Wins with strength and physicality", boosts: { strength: 18, toughness: 12, impactBlocking: 8, runBlock: 8, tackling: 8, blockShedding: 6, speed: -4, agility: -4 } },
    { key: "highMotor", name: "High Motor", description: "Max effort and coachability; raw skills for now", boosts: { effort: 20, coachability: 14, stamina: 10, discipline: 8, toughness: 6, awareness: -4, throwAccuracy: -8, catching: -8, carrying: -6, runBlock: -6, passBlock: -6, manCoverage: -6, zoneCoverage: -6, kickAccuracy: -6 } },
    { key: "fieldGeneral", name: "Field General", description: "Smart, disciplined, a leader on the field", boosts: { awareness: 16, playRecognition: 14, leadership: 16, discipline: 10, coachability: 8, speed: -2 } },
    { key: "technician", name: "Technician", description: "Polished fundamentals ahead of raw athleticism", boosts: { throwAccuracy: 10, catching: 10, ballSecurity: 10, runBlock: 8, passBlock: 8, tackling: 8, zoneCoverage: 8, kickAccuracy: 10, awareness: 6, speed: -2 } },
    { key: "balanced", name: "Balanced", description: "Solid all-around starting point", all: 4, boosts: {} },
  ],
};

const BASKETBALL: SportPreset = {
  positions: ["PG", "SG", "SF", "PF", "C", "ATH"],
  attributes: [
    { key: "speed", name: "Speed", category: "Physical" },
    { key: "acceleration", name: "Acceleration", category: "Physical" },
    { key: "agility", name: "Agility", category: "Physical" },
    { key: "strength", name: "Strength", category: "Physical" },
    { key: "vertical", name: "Vertical", category: "Physical" },
    { key: "stamina", name: "Stamina", category: "Physical" },
    { key: "bballIq", name: "Basketball IQ", category: "Mental" },
    { key: "shotSelection", name: "Shot Selection", category: "Mental" },
    { key: "discipline", name: "Discipline", category: "Mental" },
    { key: "coachability", name: "Coachability", category: "Mental" },
    { key: "insideScoring", name: "Inside Scoring", category: "Offense" },
    { key: "midRange", name: "Mid-Range", category: "Offense" },
    { key: "threePoint", name: "Three-Point", category: "Offense" },
    { key: "freeThrow", name: "Free Throw", category: "Offense" },
    { key: "ballHandling", name: "Ball Handling", category: "Offense" },
    { key: "passing", name: "Passing", category: "Offense" },
    { key: "offRebound", name: "Off. Rebounding", category: "Offense" },
    { key: "perimeterD", name: "Perimeter Defense", category: "Defense" },
    { key: "interiorD", name: "Interior Defense", category: "Defense" },
    { key: "steal", name: "Steal", category: "Defense" },
    { key: "block", name: "Block", category: "Defense" },
    { key: "defRebound", name: "Def. Rebounding", category: "Defense" },
    { key: "toughness", name: "Toughness", category: "Intangibles" },
    { key: "leadership", name: "Leadership", category: "Intangibles" },
    { key: "effort", name: "Effort / Motor", category: "Intangibles" },
  ],
  positionWeights: {
    PG: { ballHandling: 16, passing: 16, bballIq: 12, speed: 10, threePoint: 10, perimeterD: 8, shotSelection: 8, freeThrow: 5, leadership: 8, effort: 7 },
    SG: { threePoint: 16, midRange: 12, ballHandling: 10, speed: 10, perimeterD: 12, shotSelection: 8, bballIq: 8, freeThrow: 6, agility: 8, effort: 10 },
    SF: { midRange: 12, threePoint: 10, insideScoring: 10, perimeterD: 10, defRebound: 8, speed: 8, strength: 8, bballIq: 10, agility: 8, effort: 16 },
    PF: { insideScoring: 14, defRebound: 14, interiorD: 12, strength: 12, offRebound: 10, block: 8, vertical: 8, bballIq: 8, toughness: 6, effort: 8 },
    C: { interiorD: 16, defRebound: 14, insideScoring: 12, block: 12, strength: 12, offRebound: 10, vertical: 6, bballIq: 8, toughness: 10 },
    ATH: { speed: 12, agility: 10, vertical: 10, bballIq: 12, ballHandling: 8, perimeterD: 8, insideScoring: 8, effort: 18, coachability: 14 },
  },
  gradeCategories: {
    PG: ["Offense", "Defense", "Mental", "Intangibles"],
    SG: ["Offense", "Defense", "Mental", "Intangibles"],
    SF: ["Offense", "Defense", "Physical", "Intangibles"],
    PF: ["Offense", "Defense", "Physical", "Intangibles"],
    C: ["Offense", "Defense", "Physical", "Intangibles"],
    ATH: ["Offense", "Defense", "Physical", "Mental", "Intangibles"],
  },
  statDefs: [
    { key: "pts", label: "Points", group: "Scoring" },
    { key: "fgm", label: "FG Made", group: "Scoring" },
    { key: "fga", label: "FG Att", group: "Scoring" },
    { key: "tpm", label: "3P Made", group: "Scoring" },
    { key: "tpa", label: "3P Att", group: "Scoring" },
    { key: "ftm", label: "FT Made", group: "Scoring" },
    { key: "fta", label: "FT Att", group: "Scoring" },
    { key: "reb", label: "Rebounds", group: "Hustle" },
    { key: "ast", label: "Assists", group: "Hustle" },
    { key: "stl", label: "Steals", group: "Hustle" },
    { key: "blk", label: "Blocks", group: "Hustle" },
    { key: "tov", label: "Turnovers", group: "Hustle" },
  ],
  archetypes: [
    { key: "slasher", name: "Slasher", description: "Speed and bounce; jumper still developing", boosts: { speed: 16, acceleration: 14, agility: 12, vertical: 10, insideScoring: 6, threePoint: -6, strength: -4 } },
    { key: "powerBig", name: "Power Big", description: "Owns the paint and the glass", boosts: { strength: 16, interiorD: 12, defRebound: 12, offRebound: 10, insideScoring: 8, block: 8, toughness: 8, speed: -6, threePoint: -8 } },
    { key: "highMotor", name: "High Motor", description: "Max effort and coachability; raw skills for now", boosts: { effort: 20, coachability: 14, stamina: 10, discipline: 8, insideScoring: -6, midRange: -6, threePoint: -8, ballHandling: -6 } },
    { key: "floorGeneral", name: "Floor General", description: "Runs the offense with IQ and vision", boosts: { bballIq: 16, passing: 14, leadership: 14, ballHandling: 10, shotSelection: 10, discipline: 6 } },
    { key: "sharpshooter", name: "Sharpshooter", description: "Lights out from range", boosts: { threePoint: 16, midRange: 12, freeThrow: 12, shotSelection: 8, bballIq: 6, interiorD: -4, strength: -4 } },
    { key: "balanced", name: "Balanced", description: "Solid all-around starting point", all: 4, boosts: {} },
  ],
};

const SOCCER: SportPreset = {
  positions: ["GK", "CB", "FB", "CDM", "CM", "CAM", "W", "ST", "ATH"],
  attributes: [
    { key: "pace", name: "Pace", category: "Physical" },
    { key: "acceleration", name: "Acceleration", category: "Physical" },
    { key: "agility", name: "Agility", category: "Physical" },
    { key: "strength", name: "Strength", category: "Physical" },
    { key: "stamina", name: "Stamina", category: "Physical" },
    { key: "jumping", name: "Jumping", category: "Physical" },
    { key: "vision", name: "Vision", category: "Mental" },
    { key: "positioning", name: "Positioning", category: "Mental" },
    { key: "composure", name: "Composure", category: "Mental" },
    { key: "coachability", name: "Coachability", category: "Mental" },
    { key: "dribbling", name: "Dribbling", category: "Attacking" },
    { key: "firstTouch", name: "First Touch", category: "Attacking" },
    { key: "shortPassing", name: "Short Passing", category: "Attacking" },
    { key: "longPassing", name: "Long Passing", category: "Attacking" },
    { key: "finishing", name: "Finishing", category: "Attacking" },
    { key: "crossing", name: "Crossing", category: "Attacking" },
    { key: "heading", name: "Heading", category: "Attacking" },
    { key: "tacklingSoc", name: "Tackling", category: "Defending" },
    { key: "marking", name: "Marking", category: "Defending" },
    { key: "interceptions", name: "Interceptions", category: "Defending" },
    { key: "gkDiving", name: "GK Diving", category: "Goalkeeping" },
    { key: "gkHandling", name: "GK Handling", category: "Goalkeeping" },
    { key: "gkDistribution", name: "GK Distribution", category: "Goalkeeping" },
    { key: "gkPositioning", name: "GK Positioning", category: "Goalkeeping" },
    { key: "workRate", name: "Work Rate", category: "Intangibles" },
    { key: "leadership", name: "Leadership", category: "Intangibles" },
    { key: "toughness", name: "Toughness", category: "Intangibles" },
  ],
  positionWeights: {
    GK: { gkDiving: 18, gkHandling: 18, gkPositioning: 18, gkDistribution: 12, composure: 10, positioning: 6, jumping: 6, leadership: 6, coachability: 6 },
    CB: { marking: 16, tacklingSoc: 16, positioning: 14, strength: 12, heading: 10, interceptions: 10, composure: 8, jumping: 6, leadership: 8 },
    FB: { pace: 14, tacklingSoc: 12, crossing: 12, stamina: 12, marking: 10, positioning: 10, dribbling: 8, shortPassing: 8, workRate: 14 },
    CDM: { interceptions: 14, tacklingSoc: 14, shortPassing: 12, positioning: 12, vision: 10, stamina: 10, strength: 8, composure: 8, workRate: 12 },
    CM: { shortPassing: 14, vision: 12, stamina: 12, dribbling: 10, longPassing: 10, firstTouch: 10, tacklingSoc: 8, positioning: 8, workRate: 16 },
    CAM: { vision: 16, shortPassing: 14, dribbling: 14, firstTouch: 12, finishing: 10, composure: 10, agility: 8, longPassing: 6, workRate: 10 },
    W: { pace: 18, dribbling: 16, crossing: 12, acceleration: 12, finishing: 10, firstTouch: 8, agility: 8, vision: 6, workRate: 10 },
    ST: { finishing: 20, positioning: 14, firstTouch: 12, composure: 10, pace: 10, heading: 8, dribbling: 8, strength: 8, workRate: 10 },
    ATH: { pace: 14, stamina: 12, agility: 10, firstTouch: 10, shortPassing: 10, positioning: 10, workRate: 20, coachability: 14 },
  },
  gradeCategories: {
    GK: ["Goalkeeping", "Mental", "Physical", "Intangibles"],
    CB: ["Defending", "Physical", "Mental", "Intangibles"],
    FB: ["Defending", "Attacking", "Physical", "Intangibles"],
    CDM: ["Defending", "Attacking", "Mental", "Intangibles"],
    CM: ["Attacking", "Defending", "Mental", "Intangibles"],
    CAM: ["Attacking", "Mental", "Physical", "Intangibles"],
    W: ["Attacking", "Physical", "Mental", "Intangibles"],
    ST: ["Attacking", "Physical", "Mental", "Intangibles"],
    ATH: ["Attacking", "Defending", "Physical", "Mental", "Intangibles"],
  },
  statDefs: [
    { key: "goals", label: "Goals", group: "Attacking" },
    { key: "assists", label: "Assists", group: "Attacking" },
    { key: "shots", label: "Shots", group: "Attacking" },
    { key: "shotsOnTarget", label: "On Target", group: "Attacking" },
    { key: "keyPasses", label: "Key Passes", group: "Attacking" },
    { key: "tacklesWon", label: "Tackles Won", group: "Defending" },
    { key: "clearances", label: "Clearances", group: "Defending" },
    { key: "saves", label: "Saves", group: "Goalkeeping" },
    { key: "goalsConceded", label: "Goals Conceded", group: "Goalkeeping" },
    { key: "minutes", label: "Minutes", group: "General" },
    { key: "yellowCards", label: "Yellow Cards", group: "General" },
    { key: "redCards", label: "Red Cards", group: "General" },
  ],
  archetypes: [
    { key: "speedster", name: "Speedster", description: "Pace to burn; final product still developing", boosts: { pace: 18, acceleration: 16, agility: 12, stamina: 6, strength: -4, marking: -2 } },
    { key: "power", name: "Powerhouse", description: "Physically dominant in duels and in the air", boosts: { strength: 16, heading: 10, tacklingSoc: 10, jumping: 10, toughness: 10, agility: -4, pace: -2 } },
    { key: "engine", name: "Engine", description: "Runs all day, gives everything; touch still raw", boosts: { workRate: 20, stamina: 14, coachability: 12, positioning: 4, dribbling: -6, finishing: -6, firstTouch: -4 } },
    { key: "playmaker", name: "Playmaker", description: "Vision and technique between the lines", boosts: { vision: 16, shortPassing: 12, firstTouch: 12, dribbling: 10, composure: 10, longPassing: 8 } },
    { key: "balanced", name: "Balanced", description: "Solid all-around starting point", all: 4, boosts: {} },
  ],
};

const BASEBALL: SportPreset = {
  positions: ["P", "C", "1B", "2B", "3B", "SS", "LF", "CF", "RF", "DH", "UTIL"],
  attributes: [
    { key: "speed", name: "Speed", category: "Physical" },
    { key: "strength", name: "Strength", category: "Physical" },
    { key: "agility", name: "Agility", category: "Physical" },
    { key: "stamina", name: "Stamina", category: "Physical" },
    { key: "baseballIq", name: "Baseball IQ", category: "Mental" },
    { key: "plateDiscipline", name: "Plate Discipline", category: "Mental" },
    { key: "focus", name: "Focus", category: "Mental" },
    { key: "coachability", name: "Coachability", category: "Mental" },
    { key: "contact", name: "Contact", category: "Hitting" },
    { key: "power", name: "Power", category: "Hitting" },
    { key: "bunting", name: "Bunting", category: "Hitting" },
    { key: "baserunning", name: "Baserunning", category: "Hitting" },
    { key: "fielding", name: "Fielding", category: "Fielding" },
    { key: "armStrength", name: "Arm Strength", category: "Fielding" },
    { key: "armAccuracy", name: "Arm Accuracy", category: "Fielding" },
    { key: "range", name: "Range", category: "Fielding" },
    { key: "catcherSkills", name: "Catcher Skills", category: "Fielding" },
    { key: "velocity", name: "Velocity", category: "Pitching" },
    { key: "control", name: "Control", category: "Pitching" },
    { key: "movement", name: "Movement", category: "Pitching" },
    { key: "pitchStamina", name: "Pitch Stamina", category: "Pitching" },
    { key: "toughness", name: "Toughness", category: "Intangibles" },
    { key: "leadership", name: "Leadership", category: "Intangibles" },
    { key: "effort", name: "Effort / Hustle", category: "Intangibles" },
  ],
  positionWeights: {
    P: { velocity: 18, control: 18, movement: 16, pitchStamina: 12, fielding: 6, focus: 10, baseballIq: 8, toughness: 6, coachability: 6 },
    C: { catcherSkills: 18, armStrength: 12, armAccuracy: 10, fielding: 10, contact: 10, power: 6, baseballIq: 12, leadership: 12, toughness: 10 },
    "1B": { contact: 16, power: 16, fielding: 12, plateDiscipline: 10, armAccuracy: 6, baseballIq: 10, strength: 10, focus: 10, effort: 10 },
    "2B": { fielding: 16, range: 14, contact: 14, armAccuracy: 10, speed: 10, plateDiscipline: 8, baserunning: 8, baseballIq: 10, effort: 10 },
    "3B": { fielding: 14, armStrength: 14, contact: 12, power: 12, range: 8, plateDiscipline: 8, agility: 10, baseballIq: 10, toughness: 12 },
    SS: { range: 16, fielding: 16, armStrength: 12, contact: 12, speed: 10, agility: 10, baserunning: 6, baseballIq: 10, effort: 8 },
    LF: { contact: 14, power: 12, fielding: 12, range: 10, speed: 10, armStrength: 8, plateDiscipline: 10, baseballIq: 8, effort: 16 },
    CF: { speed: 16, range: 16, fielding: 12, contact: 12, baserunning: 10, armStrength: 6, plateDiscipline: 8, baseballIq: 8, effort: 12 },
    RF: { armStrength: 16, contact: 12, power: 12, fielding: 12, range: 8, speed: 8, plateDiscipline: 10, baseballIq: 8, effort: 14 },
    DH: { contact: 20, power: 20, plateDiscipline: 16, baseballIq: 10, focus: 12, strength: 10, effort: 12 },
    UTIL: { fielding: 12, contact: 12, range: 10, speed: 10, armAccuracy: 8, plateDiscipline: 8, baseballIq: 12, coachability: 14, effort: 14 },
  },
  gradeCategories: {
    P: ["Pitching", "Fielding", "Mental", "Intangibles"],
    C: ["Fielding", "Hitting", "Mental", "Intangibles"],
    "1B": ["Hitting", "Fielding", "Mental", "Intangibles"],
    "2B": ["Fielding", "Hitting", "Physical", "Intangibles"],
    "3B": ["Fielding", "Hitting", "Physical", "Intangibles"],
    SS: ["Fielding", "Hitting", "Physical", "Intangibles"],
    LF: ["Hitting", "Fielding", "Physical", "Intangibles"],
    CF: ["Fielding", "Hitting", "Physical", "Intangibles"],
    RF: ["Hitting", "Fielding", "Physical", "Intangibles"],
    DH: ["Hitting", "Mental", "Physical", "Intangibles"],
    UTIL: ["Hitting", "Fielding", "Physical", "Mental", "Intangibles"],
  },
  statDefs: [
    { key: "ab", label: "At Bats", group: "Batting" },
    { key: "hits", label: "Hits", group: "Batting" },
    { key: "doubles", label: "2B", group: "Batting" },
    { key: "triples", label: "3B", group: "Batting" },
    { key: "hr", label: "HR", group: "Batting" },
    { key: "rbi", label: "RBI", group: "Batting" },
    { key: "runs", label: "Runs", group: "Batting" },
    { key: "walks", label: "Walks", group: "Batting" },
    { key: "strikeouts", label: "SO", group: "Batting" },
    { key: "sb", label: "SB", group: "Batting" },
    { key: "ip", label: "IP", group: "Pitching" },
    { key: "er", label: "ER", group: "Pitching" },
    { key: "pitchKs", label: "K", group: "Pitching" },
    { key: "pitchBBs", label: "BB", group: "Pitching" },
  ],
  archetypes: [
    { key: "speedster", name: "Speedster", description: "Burner on the bases and in the field", boosts: { speed: 18, baserunning: 14, agility: 12, range: 10, contact: 4, power: -6 } },
    { key: "slugger", name: "Slugger", description: "Big power bat; trades some contact and speed", boosts: { power: 18, strength: 14, armStrength: 8, toughness: 6, contact: -2, speed: -4 } },
    { key: "highMotor", name: "High Motor", description: "Max hustle and coachability; raw skills for now", boosts: { effort: 20, coachability: 14, focus: 10, baseballIq: 6, contact: -6, fielding: -4, power: -6 } },
    { key: "gamer", name: "Gamer", description: "High baseball IQ and plate discipline", boosts: { baseballIq: 14, plateDiscipline: 12, focus: 12, leadership: 10, fielding: 6, contact: 4 } },
    { key: "balanced", name: "Balanced", description: "Solid all-around starting point", all: 4, boosts: {} },
  ],
};

export const PRESETS: Record<string, SportPreset> = {
  Football: FOOTBALL,
  Basketball: BASKETBALL,
  Soccer: SOCCER,
  Baseball: BASEBALL,
};

export function getPreset(sport: string | null | undefined): SportPreset {
  return PRESETS[sport ?? ""] ?? FOOTBALL;
}
